project:
  type: website

website:
  title: "The AI Blog"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/nepalprabin
      - icon: linkedin
        href: https://linkedin.com/in/prabin-nepal
format:
  html:
    theme:
      dark: cyborg
      light: flatly
    css: styles.css
